name: commitpack_objc
text_field: new_contents
pipeline:
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_redux_combined
          lower_bound: 0.2
    - name: float_filter
      kwargs:
          float_field: metadata.stack_edu_commit_message_combined
          lower_bound: 0.2
