name: commitpack_filter
text_field: text
pipeline:
    - name: float_filter  # things that don't compress well
      step: gzip_compression_p01
      kwargs:
          float_field: metadata.gzip_compression_ratio
          lower_bound: 0.054266
    - name: float_filter  # things that are super compressable
      step: gzip_compression_p99
      kwargs:
          float_field: metadata.gzip_compression_ratio
          upper_bound: 0.332872
    - name: float_filter
      step: quality_p00
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.103191
    - name: float_filter
      step: quality_p05
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.107751
    - name: float_filter
      step: quality_p10
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.113318
    - name: float_filter
      step: quality_p15
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.181589
    - name: float_filter
      step: quality_p20
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.353837
    - name: float_filter
      step: quality_p25
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.360794
    - name: float_filter
      step: quality_p30
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.365918
    - name: float_filter
      step: quality_p35
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.371319
    - name: float_filter
      step: quality_p40
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.377050
    - name: float_filter
      step: quality_p45
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.381876
    - name: float_filter
      step: quality_p50
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.387727
    - name: float_filter
      step: quality_p55
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.394878
    - name: float_filter
      step: quality_p60
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.405296
    - name: float_filter
      step: quality_p65
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.419464
    - name: float_filter
      step: quality_p70
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.487084
    - name: float_filter
      step: quality_p75
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.514745
    - name: float_filter
      step: quality_p80
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.532321
    - name: float_filter
      step: quality_p85
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.569296
    - name: float_filter
      step: quality_p90
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.654939
    - name: float_filter
      step: quality_p95
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 1000
