name: commitpack_filter
text_field: text
pipeline:
    - name: float_filter  # things that don't compress well
      step: gzip_compression_p01
      kwargs:
          float_field: metadata.gzip_compression_ratio
          lower_bound: 0.049699
    - name: float_filter  # things that are super compressable
      step: gzip_compression_p99
      kwargs:
          float_field: metadata.gzip_compression_ratio
          upper_bound: 0.384105
    - name: float_filter
      step: quality_p00
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.112908
    - name: float_filter
      step: quality_p05
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.117737
    - name: float_filter
      step: quality_p10
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.128020
    - name: float_filter
      step: quality_p15
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.218714
    - name: float_filter
      step: quality_p20
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.297422
    - name: float_filter
      step: quality_p25
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.359868
    - name: float_filter
      step: quality_p30
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.382521
    - name: float_filter
      step: quality_p35
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.391381
    - name: float_filter
      step: quality_p40
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.395298
    - name: float_filter
      step: quality_p45
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.400819
    - name: float_filter
      step: quality_p50
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.405670
    - name: float_filter
      step: quality_p55
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.410179
    - name: float_filter
      step: quality_p60
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.414693
    - name: float_filter
      step: quality_p65
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.420800
    - name: float_filter
      step: quality_p70
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.429170
    - name: float_filter
      step: quality_p75
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.443590
    - name: float_filter
      step: quality_p80
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.534875
    - name: float_filter
      step: quality_p85
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.558387
    - name: float_filter
      step: quality_p90
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.654103
    - name: float_filter
      step: quality_p95
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 1000
