name: dclm
text_field: text
pipeline:
  - name: url_substring_filter
    kwargs:
      url_key: metadata.WARC-Target-URI
      banlist_file: examples/dclm/refinedweb_banned_domains_curated.txt
      exact_domain_match: true
      ignore_chars: ['www']
  - name: url_substring_filter
    kwargs:
      url_key: metadata.WARC-Target-URI
      banlist_file: examples/dclm/refinedweb_banned_words_strict_reverse_engineered.txt
      ignore_chars: ['-', '.']
  - name: url_substring_filter
    kwargs:
      url_key: metadata.WARC-Target-URI
      banlist_file: examples/dclm/refinedweb_banned_words_hard_reverse_engineered.txt
      match_substrings: false
  - name: url_substring_filter
    kwargs:
      url_key: metadata.WARC-Target-URI
      banlist_file: examples/dclm/refinedweb_banned_words_soft_reverse_engineered.txt
      num_banned_substrs: 2
      match_substrings: false
  - name: url_substring_filter
    kwargs:
      url_key: metadata.WARC-Target-URI
      banlist_file: examples/all_dressed/fineweb_url_filters/domains.txt
      exact_domain_match: true
  - name: url_substring_filter
    kwargs:
      url_key: metadata.WARC-Target-URI
      banlist_file: examples/all_dressed/fineweb_url_filters/domains.txt
      exact_subdomain_match: true
  - name: url_substring_filter
    kwargs:
      url_key: metadata.WARC-Target-URI
      banlist_file: examples/all_dressed/fineweb_url_filters/urls.txt
      exact_url_match: true
  - name: url_substring_filter
    kwargs:
      url_key: metadata.WARC-Target-URI
      banlist_file: examples/all_dressed/fineweb_url_filters/banned_words.txt
      exact_part_match: true      
  - name: url_substring_filter
    kwargs:
      url_key: metadata.WARC-Target-URI
      banlist_file: examples/all_dressed/fineweb_url_filters/soft_banned_words.txt
      match_substrings: false
      num_banned_substrs: 2
  - name: url_substring_filter
    kwargs:
      url_key: metadata.WARC-Target-URI
      banlist_file: examples/all_dressed/fineweb_url_filters/banned_subwords.txt
      match_substrings: true
  - name: newline_removal_modifier
    kwargs:
      max_consecutive: 2
  - name: fasttext_annotator
    kwargs:
      #fast_text_file: examples/dclm/models--cis-lmu--glotlid/snapshots/74cb50b709c9eefe0f790030c6c95c461b4e3b77/model.bin
      fast_text_file: examples/dclm/lid.176.bin
      output_field: metadata.lang
  - name: float_filter
    kwargs:
      #float_field: metadata.lang.__label__eng_Latn
      float_field: metadata.lang.__label__en
      lower_bound: 0.65
      default: 0.0
  - name: page_len_filter
    kwargs:
      length_type: word
      lower_bound: 50
      upper_bound: 100000
      ignore_punctuation: true
  - name: word_len_filter
    kwargs:
      lower_bound: 3
      upper_bound: 10
  - name: symbol_ratio_filter
    kwargs:
      max_symbol_to_word_ratio: 0.1
  - name: bullet_filter
    kwargs:
      max_bullet_ratio: 0.9        
  - name: ellipsis_line_ratio_filter
    kwargs:
      max_ratio: 0.3      
  - name: alphabetic_word_ratio_filter
    kwargs:
      max_ratio: 0.2
  - name: stop_word_filter
    kwargs:
      count_unique: false
      min_stop_word: 2
  - name: massive_web_repetition_filter
  - name: word_count_adder
    kwargs:
      word_count_field: original_word_count
  - name: ratio_line_modifier
    kwargs:
      upper_bound: 0.5
      check: uppercase
  - name: ratio_line_modifier
    kwargs:
      upper_bound: 0.999999
      check: numeric
  - name: regex_line_modifier
    kwargs: 
      regex_string: '^\W*\d(?:,|\.|\d)*(?:K|k|M|m|B|b)?\s+(?:likes|shares|comments|retweets|reposts|quotes|bookmarks|upvotes|downvotes|downloads|views|followers)\W*'
  - name: line_len_modifier
    kwargs:
      lower_bound: 2
  - name: substring_line_modifier
    kwargs:
      banlist: "items in cart"
      max_length: 10
      remove_substring_only: true
  - name: substring_line_modifier
    kwargs:
      banlist: "Read more..."
      max_length: 10
      remove_substring_only: true
      location: suffix
  - name: substring_line_modifier
    kwargs:
      banlist: "Sign-in"
      max_length: 10
      remove_substring_only: true
      location: prefix
  - name: word_removal_ratio_filter
    kwargs:
      word_count_field: original_word_count
      upper_bound: 0.05
  - name: madlad400_sentence_filter
    kwargs:
      fast_text_file: examples/dclm/lid.176.bin
      langid_field: metadata.lang
      cursed_regex_file: examples/dclm/madlad400_cursed.txt