name: fuzzy_suffarr
text_field: text
pipeline:
  - name: interval_filter
    kwargs:
      text_field: text
      interval_field: sa_remove_ranges
      fuzzy_merge: true
      merge_fuzziness: 0.95
      output_text_field: text