name: quality_vigintiles
text_field: text
pipeline:
    - name: float_filter
      step: vigintile_0000
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.0017086865846067667
    - name: float_filter
      step: vigintile_0001
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.003763043787330389
    - name: float_filter
      step: vigintile_0002
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.006234203465282917
    - name: float_filter
      step: vigintile_0003
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.009215031750500202
    - name: float_filter
      step: vigintile_0004
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.012857586145401001
    - name: float_filter
      step: vigintile_0005
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.01721642166376114
    - name: float_filter
      step: vigintile_0006
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.022270619869232178
    - name: float_filter
      step: vigintile_0007
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.028381623327732086
    - name: float_filter
      step: vigintile_0008
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.03596179932355881
    - name: float_filter
      step: vigintile_0009
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.04507845267653465
    - name: float_filter
      step: vigintile_0010
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.05577823147177696
    - name: float_filter
      step: vigintile_0011
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.0678863599896431
    - name: float_filter
      step: vigintile_0012
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.08078984916210175
    - name: float_filter
      step: vigintile_0013
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.09517112374305725
    - name: float_filter
      step: vigintile_0014
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.11319341510534286
    - name: float_filter
      step: vigintile_0015
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.13781428337097168
    - name: float_filter
      step: vigintile_0016
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.17539729177951813
    - name: float_filter
      step: vigintile_0017
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.2382344901561737
    - name: float_filter
      step: vigintile_0018
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.36179280281066895
    - name: float_filter
      step: vigintile_0019
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 1000
