name: quality_vigintiles
text_field: text
pipeline:
    - name: float_filter
      step: vigintile_0000
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.010594391264021397
    - name: float_filter
      step: vigintile_0001
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.024246975779533386
    - name: float_filter
      step: vigintile_0002
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.04028526321053505
    - name: float_filter
      step: vigintile_0003
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.058916375041007996
    - name: float_filter
      step: vigintile_0004
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.08035200834274292
    - name: float_filter
      step: vigintile_0005
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.10486985743045807
    - name: float_filter
      step: vigintile_0006
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.13288825750350952
    - name: float_filter
      step: vigintile_0007
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.16529496014118195
    - name: float_filter
      step: vigintile_0008
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.20338039100170135
    - name: float_filter
      step: vigintile_0009
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.24875041842460632
    - name: float_filter
      step: vigintile_0010
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.3026883602142334
    - name: float_filter
      step: vigintile_0011
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.3659166693687439
    - name: float_filter
      step: vigintile_0012
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.4388523995876312
    - name: float_filter
      step: vigintile_0013
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.5202486515045166
    - name: float_filter
      step: vigintile_0014
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.6057307124137878
    - name: float_filter
      step: vigintile_0015
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.6909273266792297
    - name: float_filter
      step: vigintile_0016
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.7729188799858093
    - name: float_filter
      step: vigintile_0017
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.8507325053215027
    - name: float_filter
      step: vigintile_0018
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.9287170767784119
    - name: float_filter
      step: vigintile_0019
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 1000
