name: quality_vigintiles
text_field: text
pipeline:
    - name: float_filter
      step: vigintile_0000
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.0011564408196136355
    - name: float_filter
      step: vigintile_0001
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.0027779471129179
    - name: float_filter
      step: vigintile_0002
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.004797319881618023
    - name: float_filter
      step: vigintile_0003
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.007188483141362667
    - name: float_filter
      step: vigintile_0004
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.009960709139704704
    - name: float_filter
      step: vigintile_0005
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.013215738348662853
    - name: float_filter
      step: vigintile_0006
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.017105478793382645
    - name: float_filter
      step: vigintile_0007
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.021838106215000153
    - name: float_filter
      step: vigintile_0008
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.027642250061035156
    - name: float_filter
      step: vigintile_0009
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.034812990576028824
    - name: float_filter
      step: vigintile_0010
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.04374740272760391
    - name: float_filter
      step: vigintile_0011
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.055064186453819275
    - name: float_filter
      step: vigintile_0012
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.0697297751903534
    - name: float_filter
      step: vigintile_0013
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.08942069113254547
    - name: float_filter
      step: vigintile_0014
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.1169658750295639
    - name: float_filter
      step: vigintile_0015
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.15766307711601257
    - name: float_filter
      step: vigintile_0016
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.22276301681995392
    - name: float_filter
      step: vigintile_0017
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.3380826711654663
    - name: float_filter
      step: vigintile_0018
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.5717012882232666
    - name: float_filter
      step: vigintile_0019
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 1000
