name: quality_vigintiles
text_field: text
pipeline:
    - name: float_filter
      step: vigintile_0000
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.043963927775621414
    - name: float_filter
      step: vigintile_0001
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.10066636651754379
    - name: float_filter
      step: vigintile_0002
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.15660260617733002
    - name: float_filter
      step: vigintile_0003
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.212627112865448
    - name: float_filter
      step: vigintile_0004
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.276346355676651
    - name: float_filter
      step: vigintile_0005
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.34856870770454407
    - name: float_filter
      step: vigintile_0006
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.4286263883113861
    - name: float_filter
      step: vigintile_0007
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.5120196342468262
    - name: float_filter
      step: vigintile_0008
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.5922344923019409
    - name: float_filter
      step: vigintile_0009
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.6651713848114014
    - name: float_filter
      step: vigintile_0010
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.7286219596862793
    - name: float_filter
      step: vigintile_0011
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.783191442489624
    - name: float_filter
      step: vigintile_0012
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.8299219012260437
    - name: float_filter
      step: vigintile_0013
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.8696004152297974
    - name: float_filter
      step: vigintile_0014
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.9032395482063293
    - name: float_filter
      step: vigintile_0015
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.9314584732055664
    - name: float_filter
      step: vigintile_0016
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.9548373818397522
    - name: float_filter
      step: vigintile_0017
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.973965585231781
    - name: float_filter
      step: vigintile_0018
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.9895029067993164
    - name: float_filter
      step: vigintile_0019
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 1000
