name: quality_vigintiles
text_field: text
pipeline:
    - name: float_filter
      step: vigintile_0000
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.003441114444285631
    - name: float_filter
      step: vigintile_0001
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.00790475681424141
    - name: float_filter
      step: vigintile_0002
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.01269710622727871
    - name: float_filter
      step: vigintile_0003
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.0185701847076416
    - name: float_filter
      step: vigintile_0004
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.02574974298477173
    - name: float_filter
      step: vigintile_0005
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.03386564925312996
    - name: float_filter
      step: vigintile_0006
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.04267558455467224
    - name: float_filter
      step: vigintile_0007
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.053457681089639664
    - name: float_filter
      step: vigintile_0008
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.06669725477695465
    - name: float_filter
      step: vigintile_0009
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.0827251523733139
    - name: float_filter
      step: vigintile_0010
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.10210539400577545
    - name: float_filter
      step: vigintile_0011
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.12573526799678802
    - name: float_filter
      step: vigintile_0012
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.15495438873767853
    - name: float_filter
      step: vigintile_0013
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.19167815148830414
    - name: float_filter
      step: vigintile_0014
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.23848196864128113
    - name: float_filter
      step: vigintile_0015
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.2993033528327942
    - name: float_filter
      step: vigintile_0016
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.38334226608276367
    - name: float_filter
      step: vigintile_0017
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.5100736021995544
    - name: float_filter
      step: vigintile_0018
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 0.7110226154327393
    - name: float_filter
      step: vigintile_0019
      kwargs:
          float_field: metadata.ultrafineweb.__label__pos
          lower_bound: 1000
