name: ft_annotator
text_field: text
pipeline:
  - name: fasttext_annotator
    kwargs:
      fast_text_file: /home/ec2-user/fasttext_resources/code-vs-code/model/MODEL_NAME_REPLACE_ME.bin
      output_field: metadata.code_vs_code
