name: filter_out_bad_paths
text_field: text
pipeline: 
  - name: deny_list_filter
    kwargs:
      attribute_field: metadata.Source-File
      deny_list_file: "/mnt/raid0/all_take23_take25_take27_paths.txt"