name: commitpack_filter
text_field: text
pipeline:
    - name: diff_annotator
      step: combine_diff
      kwargs:
          before_field: old_contents
          after_field: new_contents
          message_field: commit_to_request_short.feature_request
          output_field: text
    - name: string_eq_filter # cannot make commits into feature requests
      text_field: commit_to_request_short.feature_request
      keep_matches: false
      eq: "N/A"
      step: invalid_request
    - name: float_filter  # things that don't compress well
      step: gzip_compression_p01
      kwargs:
          float_field: metadata.gzip_compression_ratio
          lower_bound: 0.092025
    - name: float_filter  # things that are super compressable
      step: gzip_compression_p99
      kwargs:
          float_field: metadata.gzip_compression_ratio
          upper_bound: 0.444471
    - name: float_filter
      step: quality_p00
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.113359
    - name: float_filter
      step: quality_p05
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.121900
    - name: float_filter
      step: quality_p10
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.370372
    - name: float_filter
      step: quality_p15
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.388257
    - name: float_filter
      step: quality_p20
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.393688
    - name: float_filter
      step: quality_p25
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.397759
    - name: float_filter
      step: quality_p30
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.401259
    - name: float_filter
      step: quality_p35
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.403624
    - name: float_filter
      step: quality_p40
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.406065
    - name: float_filter
      step: quality_p45
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.407338
    - name: float_filter
      step: quality_p50
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.408726
    - name: float_filter
      step: quality_p55
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.410070
    - name: float_filter
      step: quality_p60
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.411526
    - name: float_filter
      step: quality_p65
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.413331
    - name: float_filter
      step: quality_p70
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.415781
    - name: float_filter
      step: quality_p75
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.420368
    - name: float_filter
      step: quality_p80
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.554201
    - name: float_filter
      step: quality_p85
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.563866
    - name: float_filter
      step: quality_p90
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.672364
    - name: float_filter
      step: quality_p95
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 1000
