name: commitpack_filter
text_field: text
pipeline:
    - name: diff_annotator
      step: combine_diff
      kwargs:
          before_field: old_contents
          after_field: new_contents
          message_field: commit_to_request_short.feature_request
          output_field: text
    - name: string_eq_filter # cannot make commits into feature requests
      step: invalid_request
      kwargs:
        str_field: commit_to_request_short.feature_request
        keep_matches: false
        eq: "N/A"
    - name: float_filter  # things that don't compress well
      step: gzip_compression_p01
      kwargs:
          float_field: metadata.gzip_compression_ratio
          lower_bound: 0.087740
    - name: float_filter  # things that are super compressable
      step: gzip_compression_p99
      kwargs:
          float_field: metadata.gzip_compression_ratio
          upper_bound: 0.469074
    - name: float_filter
      step: quality_p00
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.103752
    - name: float_filter
      step: quality_p05
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.113947
    - name: float_filter
      step: quality_p10
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.170456
    - name: float_filter
      step: quality_p15
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.293846
    - name: float_filter
      step: quality_p20
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.332974
    - name: float_filter
      step: quality_p25
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.347323
    - name: float_filter
      step: quality_p30
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.355568
    - name: float_filter
      step: quality_p35
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.363152
    - name: float_filter
      step: quality_p40
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.368506
    - name: float_filter
      step: quality_p45
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.374501
    - name: float_filter
      step: quality_p50
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.381897
    - name: float_filter
      step: quality_p55
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.387793
    - name: float_filter
      step: quality_p60
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.394362
    - name: float_filter
      step: quality_p65
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.401922
    - name: float_filter
      step: quality_p70
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.408789
    - name: float_filter
      step: quality_p75
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.419366
    - name: float_filter
      step: quality_p80
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.441600
    - name: float_filter
      step: quality_p85
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.511647
    - name: float_filter
      step: quality_p90
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.577289
    - name: float_filter
      step: quality_p95
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 1000
