name: commitpack_filter
text_field: text
pipeline:
    - name: diff_annotator
      step: combine_diff
      kwargs:
          before_field: old_contents
          after_field: new_contents
          message_field: commit_to_request_short.feature_request
          output_field: text
    - name: string_eq_filter # cannot make commits into feature requests
      text_field: commit_to_request_short.feature_request
      keep_matches: false
      eq: "N/A"
      step: invalid_request
    - name: float_filter  # things that don't compress well
      step: gzip_compression_p01
      kwargs:
          float_field: metadata.gzip_compression_ratio
          lower_bound: 0.076399
    - name: float_filter  # things that are super compressable
      step: gzip_compression_p99
      kwargs:
          float_field: metadata.gzip_compression_ratio
          upper_bound: 0.662708
    - name: float_filter
      step: quality_p00
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.102778
    - name: float_filter
      step: quality_p05
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.114245
    - name: float_filter
      step: quality_p10
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.121390
    - name: float_filter
      step: quality_p15
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.159624
    - name: float_filter
      step: quality_p20
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.197367
    - name: float_filter
      step: quality_p25
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.258859
    - name: float_filter
      step: quality_p30
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.316656
    - name: float_filter
      step: quality_p35
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.339818
    - name: float_filter
      step: quality_p40
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.358246
    - name: float_filter
      step: quality_p45
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.369877
    - name: float_filter
      step: quality_p50
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.382285
    - name: float_filter
      step: quality_p55
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.394393
    - name: float_filter
      step: quality_p60
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.404768
    - name: float_filter
      step: quality_p65
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.412952
    - name: float_filter
      step: quality_p70
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.418993
    - name: float_filter
      step: quality_p75
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.424745
    - name: float_filter
      step: quality_p80
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.437227
    - name: float_filter
      step: quality_p85
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.468733
    - name: float_filter
      step: quality_p90
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 0.547946
    - name: float_filter
      step: quality_p95
      kwargs:
          float_field: metadata.combined_quality_score
          lower_bound: 1000
