name: olmocr
text_field: text
pipeline:
  - name: olmocr_rules_adder
  - name: float_filter
    kwargs:
      float_field: metadata.olmocr_rules.table_lines_ratio
      upper_bound: 0.3
      default: 1.0
  - name: float_filter
    kwargs:
      float_field: metadata.olmocr_rules.digits_ratio
      upper_bound: 0.1
      default: 1.0
  - name: fasttext_annotator
    kwargs:
      fast_text_file: /mnt/raid0/models/lid.176.bin
      output_field: metadata.lang
  - name: float_filter
    kwargs:
      float_field: metadata.lang.__label__en
      lower_bound: 0.50
      default: 0.0
  # - name: fasttext_annotator
  #   kwargs:
  #     fast_text_file: /mnt/raid0/models/openhermes_reddit_eli5_vs_rw_v2_bigram_200k_train.bin
  #     output_field: metadata.dclm_quality
  # - name: float_filter
  #   kwargs:
  #     float_field: metadata.dclm_quality.__label__hq
  #     # lower_bound: 0.018112 # DCLM baseline
  #     # lower_bound: 0.03311014 # DCLM HQ
  #     lower_bound: 0.001
  #     default: 0.0
  - name: fasttext_annotator
    kwargs:
      fast_text_file: /mnt/raid0/models/fineweb_edu_gt2_bigram_200k.bin
      output_field: metadata.fineweb_edu
  - name: float_filter
    kwargs:
      float_field: metadata.fineweb_edu.__label__1
      # lower_bound: 0.10
      # lower_bound: 0.30
      lower_bound: 0.01
      default: 0.0
