name: fim_test_04022025
text_field: text
pipeline:
  # Just get python anly
  - name: string_eq_filter 
    kwargs:
      text_field: metadata.language 
      targets:
        - python    
      case_sensitive: false
  # Escape special characters
  - name: string_sub_modifier
    kwargs:
      text_field: text
      subs:
        - ['<|endoftext|>', '<|\U0010f0f0endoftext|>']
        - ['<|fim_prefix|>', '<|\U0010f0f0fim_prefix|>']
        - ['<|fim_middle|>', '<|\U0010f0f0fim_middle|>']
        - ['<|fim_suffix|>', '<|\U0010f0f0fim_suffix|>']
        - ['<|im_start|>', '<|\U0010f0f0im_start|>']
        - ['<|im_end|>', '<|\U0010f0f0im_end|>']
        - ['<|endofprompt|>', '<|\U0010f0f0endofprompt|>']
        - ['<|pad|>', '<|\U0010f0f0pad|>']
        - ['<|repo_name|>', '<|\U0010f0f0repo_name|>']
        - ['<|file_sep|>', '<|\U0010f0f0file_sep|>']        
group_pipeline:
  - group_key: 
    - metadata.repo_name
    group_ops:
      - name: concatenate
        kwargs: 
          text_cat_field: text 
          join_string: "\n<|file_sep|>\n"
