name: fim_test_04022025
text_field: text
pipeline:
  # Just get python anly
  - name: string_eq_filter 
    kwargs:
      text_field: metadata.language 
      targets:
        - python    
      case_sensitive: false
  # Escape special characters
  - name: string_sub_modifier
    kwargs:
      text_field: text
      subs:
        - ['<|endoftext|>', '<|􏃰endoftext|>']
        - ['<|fim_prefix|>', '<|􏃰fim_prefix|>']
        - ['<|fim_middle|>', '<|􏃰fim_middle|>']
        - ['<|fim_suffix|>', '<|􏃰fim_suffix|>']
        - ['<|im_start|>', '<|􏃰im_start|>']
        - ['<|im_end|>', '<|􏃰im_end|>']
        - ['<|endofprompt|>', '<|􏃰endofprompt|>']
        - ['<|pad|>', '<|􏃰pad|>']
        - ['<|repo_name|>', '<|􏃰repo_name|>']
        - ['<|file_sep|>', '<|􏃰file_sep|>']        
group_pipeline:
  - group_key: 
    - metadata.repo_name
    group_ops:
      - name: concatenate
        kwargs: 
          text_cat_field: text 
          join_string: "\n<|file_sep|>\n"
