name: jupyter_notebook_commitpack_classifier
pipeline:
    - name: gzip_annotator
      kwargs:
          text_field: new_contents
          anno_field: metadata.gzip_compression_ratio

    - name: ultrafineweb_annotator
      kwargs:
          text_field: new_contents
          output_field: metadata.stack_edu_redux
          max_text_length: 10000
          fast_text_file: /mnt/raid0/ai2-llm/classifiers/code-quality/trained_models/fasttext/stack_edu_redux_ultrafine_bin5/jupyter_notebook/model.bin
    - name: linear_transform_annotator
      kwargs:
          features:
              - field: metadata.stack_edu_redux.__label__bin1
                weight: -0.49716
              - field: metadata.stack_edu_redux.__label__bin2
                weight: -0.23606
              - field: metadata.stack_edu_redux.__label__bin3
                weight: 0.015159
              - field: metadata.stack_edu_redux.__label__bin4
                weight: 0.32222
              - field: metadata.stack_edu_redux.__label__bin5
                weight: 0.39449
          bias: 0.475797
          output_field: metadata.stack_edu_redux_combined

    - name: ultrafine_commit_annotator
      kwargs:
          text_field: message
          output_field: metadata.stack_edu_commit_message
          max_text_length: 10000
          fast_text_file: /mnt/raid0/ai2-llm/classifiers/code-quality/trained_models/fasttext/commitpack_commit_message_ultrafine_commits_bin5/model.bin
    - name: linear_transform_annotator
      kwargs:
          features:
              - field: metadata.stack_edu_commit_message.__label__bin1
                weight: -0.454059
              - field: metadata.stack_edu_commit_message.__label__bin2
                weight: -0.218452
              - field: metadata.stack_edu_commit_message.__label__bin3
                weight: 0.009999
              - field: metadata.stack_edu_commit_message.__label__bin4
                weight: 0.272796
              - field: metadata.stack_edu_commit_message.__label__bin5
                weight: 0.390171
          bias: 0.474003
          output_field: metadata.stack_edu_commit_message_combined

    - name: jq_annotator
      kwargs:
          expression: '((.metadata.stack_edu_redux_combined // 0 | [., 1] | min | [., 0] | max) * (.metadata.stack_edu_commit_message_combined // 0 | [., 1] | min | [., 0] | max)) | sqrt'
          output_field: metadata.combined_quality_score

    - name: jq_annotator
      kwargs:
          expression: '((.old_contents // "") | gsub("^\\s+|\\s+$"; "")) + "\n\n\n" + ((.message // "") | gsub("^\\s+|\\s+$"; "")) + "\n\n\n" + ((.new_contents // "") | gsub("^\\s+|\\s+$"; ""))'
          output_field: text
