name: code_vs_code_JavaScript
pipeline:
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.18136
  name: float_filter
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.35047
  name: float_filter
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.53106
  name: float_filter
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.76733
  name: float_filter
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.93682
  name: float_filter
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.99423
  name: float_filter
text_field: text
