name: code_vs_code_Shell
pipeline:
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.41682
  name: float_filter
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.89653
  name: float_filter
text_field: text
