name: code_vs_code_TypeScript
pipeline:
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.24991
  name: float_filter
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.4256
  name: float_filter
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.65843
  name: float_filter
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.89631
  name: float_filter
- kwargs:
    default: 0.0
    float_field: metadata.code_vs_code._%%_label_%%_spring2code
    lower_bound: 0.99274
  name: float_filter
text_field: text
